name: teach_me
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  hexcolor: ^3.0.1
  internet_connection_checker: ^1.0.0+1
  percent_indicator: ^4.2.3
  pinput: ^2.2.31
  pusher_client: ^2.0.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  validators: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - lang/ar.json
    - lang/en.json

#fonts:
#  - family: PlusJakartaSans
#    fonts:
#      - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
#        weight: 100
#      - asset: assets/fonts/PlusJakartaSans-Light.ttf
#        weight: 300
#      - asset: assets/fonts/PlusJakartaSans-Regular.ttf
#        weight: 400
#      - asset: assets/fonts/PlusJakartaSans-Medium.ttf
#        weight: 500
#      - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
#        weight: 600
#      - asset: assets/fonts/PlusJakartaSans-Bold.ttf
#        weight: 700
#      - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
#        weight: 800
#      - asset: assets/fonts/PlusJakartaSans-ExtraLightItalic.ttf
#        weight: 100
#        style: italic
#      - asset: assets/fonts/PlusJakartaSans-LightItalic.ttf
#        weight: 300
#        style: italic
#      - asset: assets/fonts/PlusJakartaSans-Italic.ttf
#        weight: 400
#        style: italic
#      - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
#        weight: 500
#        style: italic
#      - asset: assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
#        weight: 600
#        style: italic
#      - asset: assets/fonts/PlusJakartaSans-BoldItalic.ttf
#        weight: 700
#        style: italic
#      - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
#        weight: 800
#        style: italic
#
#  - family: Inter
#    fonts:
#      - asset: assets/fonts/Inter-Thin.ttf
#        weight: 100
#      - asset: assets/fonts/Inter-ExtraLight.ttf
#        weight: 200
#      - asset: assets/fonts/Inter-Light.ttf
#        weight: 300
#      - asset: assets/fonts/Inter-Regular.ttf
#        weight: 400
#      - asset: assets/fonts/Inter-Medium.ttf
#        weight: 500
#      - asset: assets/fonts/Inter-SemiBold.ttf
#        weight: 600
#      - asset: assets/fonts/Inter-Bold.ttf
#        weight: 700
#      - asset: assets/fonts/Inter-ExtraBold.ttf
#        weight: 800
#      - asset: assets/fonts/Inter-Black.ttf
#        weight: 900
